name: My Custom Action

on:
  push:
    branches:
      - main # or master, depending on your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 24f2000970@ds.study.iitm.ac.in
      run: echo "Hello from your GitHub Action!"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
